# Generated by Django 5.2.17 on 2026-08-31 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(db_index=True, max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('sender_email', models.CharField(blank=True, max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, default='(No Subject)', max_length=998)),
                ('body_plain', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('raw_headers', models.TextField(blank=True)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('has_attachments', models.BooleanField(default=False)),
                ('attachments_info', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailboxes.emailaddress')),
            ],
            options={
                'verbose_name': 'received email',
                'verbose_name_plural': 'received emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
