# Generated by Django 5.2.17 on 2026-08-31 20:31

import apps.mailboxes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0002_emailmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='domain',
            field=models.CharField(db_index=True, default=apps.mailboxes.models.get_default_domain, max_length=255),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='local_part',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'name'], name='mailboxes_c_user_id_34d485_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['local_part', 'domain'], name='mailboxes_e_local_p_3209e3_idx'),
        ),
        migrations.AddIndex(
            model_name='emailaddress',
            index=models.Index(fields=['user', 'is_active'], name='mailboxes_e_user_id_2a6c52_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['email_address', 'is_read'], name='mailboxes_e_email_a_6d8d83_idx'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['email_address', '-created_at'], name='mailboxes_e_email_a_1f95a4_idx'),
        ),
    ]
